# Site Configuration
[site]
  title             = "BVSWebDesign" # Shared title for SEO and OpenGraph
  description       = "Website design and development in Wordpress, Wix and Squarespace - Website design for Small to Medium sized businesses based between Skipton and Keighley." # Shared description for SEO and OpenGraph
  tagline           = "Website Design and Development for growing businesses"
  taglineSeparator = "" # default is " - " 
  baseUrl          = "https://www.bvswebdesign.co.uk" # Base URL for the site and used in OpenGraph meta tags.
  logo              = "/images/bvs-logo.png" # Path to the site's logo
  logoAlternate    = "" # Path to the site's logo
  logoText         = "" # Text displayed next to the logo
  logoWidth        = "120px" # Width of the logo
  logoHeight       = "100px" # Height of the logo

  # Add a trailing slash at the end of URLs (e.g., https://example.com/, https://example.com/contact/)
  # Note: Manually restart your server when you change this value
  trailingSlash = true

  # Add your site logo in image path below and open your terminal and run "npm run generate-favicons" to generate favicons for different devices and platform (https://realfavicongenerator.net/checker)
  [site.favicon]
    path  = "/images/favicons" # favicon images path (No need to change it)
    image = "/images/bvs-logo.png" # Add your site logo path here and follow upper instruction


# SEO Metadata
# Specific SEO configurations that complement the general site settings.
# -----------------------------------------------------------------------------------------------------------------------------------
[seo]
  author   = "Steve Marks"
  keywords = [
    "digital agency", 
    "website development",
    "website design",
    "web development",
    "web design",
    "wordpress websites",
    "website maintenance",
    "website designer in skipton",
    "website designer in yorkshire",
    "help with my website"
  ]
  robots   = "index, follow" # Instructs search engines on how to crawl and index the pages.

  [seo.robotsTxt]
    enable = true # Enables or disables robots.txt file generation on site build
    disallow = [
      "/_astro/",
      "/cdn-cgi/",
    ] # Disallow specific paths (e.g., "/_astro/", "/cdn-cgi/")

  [seo.sitemap]
    enable = true # Enables or disables sitemap generation on site build
    exclude = [] # exclude all pages that include these folder names


# Different theme settings
# -----------------------------------------------------------------------------------------------------------------------------------
[settings]
  # If you change value of any of the following three, make sure to change the folder name also from
  # - "src/content" folder
  # - "src/[...lang]/pages" folder
  # - "src/content.config.ts" collection object
  blogFolder      = "blog" # Folder where blog posts are stored
  servicesFolder  = "services" # Folder where services are stored
  portfolioFolder = "portfolio" # Folder where portfolio/projects are stored

  pagination    = 4 # Number of posts displayed on each page blog list page
  stickyHeader = true # Enables scroll-aware sticky behavior (e.g., hide on scroll down), not applicable to fixed headers
  pageHeaderDefaultImage = "/images/page-header/default.png" # if you don't pass image in frontmatter of a page then this image will be used as header image

  # docs - https://formspree.io/ | https://formsubmit.co/ | https://docs.netlify.com/forms/setup/
  # Form action URL for the contact form (For more settings related to form see "src/content/sections/contact-section.md")
  contactFormAction = "https://formsubmit.co/74a69feaf4b8979bf5f8bbe463d7070d "
  # formspree | formsubmit.co | netlify (default is formsubmit.co)
  contactFormProvider = "formsubmit.co"

  footerDescription = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the footer description in different languages or directly add value here if you are not using internationalization feature

  # For changing footer description and footer copyright in different languages see src/i18n/en.json and src/i18n/fr.json
  # We kindly appreciate it if you retain the theme copyright. Thank you for supporting Getastrothemes!
  [settings.copyright]
    enable = true
    text   = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the copyright text in different languages or directly add value here if you are not using internationalization feature

  # Mailchimp Subscription Form located in footer
  [settings.subscription]
    enable      = true # Enables or disable the subscription form
    title       = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the title in different languages or directly add value here if you are not using internationalization feature
    note       = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the note in different languages or directly add value here if you are not using internationalization feature
    formAction = "https://bvswebdesign.us14.list-manage.com/subscribe/post?u=5b7b7e7aff1160aa664dc2bc7&amp;id=3c09550cc7&amp;f_id=00119fe0f0"
    mailchimpTagValue = ""
    

  # Multilingual settings (check src/config/language.json for changing the languages)
  # NOTE: Manually restart your server when you change the following multilingual table values
  [settings.multilingual]
    # Set `enable` to `true` for enabling the multilingual feature or `false` for disabling it.
    # Run `npm run remove-multilingual` for removing multilingual content files after disabling the feature.
    enable                   = false
    defaultLanguage         = "en"
    disableLanguages        = [""] # List of languages to disable (eg: ["fr", "es"])
    showDefaultLangInUrl = false # Show default language in URL (eg: https://getastrothemes.com/en/)

  # Global Contact Information
  [settings.contactInfo]
    address = ""
    email = "[info@bvswebdesign.co.uk](mailto:info@bvswebdesign.co.uk)"
    phone = "[+44 7521917508](tel:+447521917508)"

  # Header Offcanvas Configuration
  # Update social links in `src/config/social.json`
  [settings.headerOffcanvas]
    enable = true
    logo = ""
    description = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the description in different languages or directly add value here if you are not using internationalization feature. This is also used in footer of personal-portfolio homepage
    
    # Call To Action Button
    [settings.headerOffcanvas.button]
      enable = true
      label = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the button label in different languages or directly add value here if you are not using internationalization feature
      url = "https://tidycal.com/bvswebdesign/30-minute-meeting"
            
  # Navigation Button In Header
  [settings.navigationButton]
    enable = true
    label  = "" # Check src/i18n/en.json and src/i18n/fr.json for changing the navigation button label in different languages or directly add value here if you are not using internationalization feature
    url    = "https://tidycal.com/bvswebdesign/30-minute-meeting"

  [settings.markup.tableOfContents]
    enable      = true
    expanded    = false # whether to expand the table of contents by default
    endLevel    = 5
    ordered     = false
    startLevel = 1


# OpenGraph Metadata
# Specific OpenGraph settings, using values from the [site] section where possible.
# -----------------------------------------------------------------------------------------------------------------------------------
[opengraph]
  image        = "/images/og-image.jpg" # Image used in OpenGraph previews
  ogLocale    = "en_US" # Locale setting for OpenGraph
  ogType      = "website" # Type of content for OpenGraph protocol
  twitter      = "" # Twitter handle for Twitter Card meta tags
  twitterCard = "summary_large_image" # Type of Twitter Card to use in social sharing

# [head] (Add custom scripts, stylesheets, and meta tags to be rendered in the <head> section of the page)
# -----------------------------------------------------------------------------------------------------------------------------------
[head]
  content = """
  <noscript defer src="/umami.is.js" data-website-id=""></noscript>
  """
